### ISSUE TITLE
It's been six hours...

### ISSUE THREAD

**Issue by d-e-s-o** [ridiculousfish/git-prev-next#4]
...and I am still laughing about your ["line noise"](https://github.com/ridiculousfish/git-prev-next/commit/1d8daa240f4737cba6a8d8edc9c6200924e73e23) comment ;-)

(sorry for the breakage...)

**Comment by d-e-s-o** [comment]
'nuff said.

**Comment by ridiculousfish** [comment]
No worries at all!
